### ISSUE TITLE
time.sleep inaccuracy

### ISSUE THREAD

**Issue by NotTheEconomist** [NotTheEconomist/Timeclock#2]
`time.sleep(1)` will slowly lose time, since the process will only get control back SOMETIME AFTER one second has passed.

**Comment by NotTheEconomist** [comment]
On second thought, so long as our time compare gets done properly (and not just `time.sleep(1); seconds += 1` it doesn't matter if we lose a few milliseconds.

**Comment by minorsecond** [comment]
On the scale that I personally will use it, I think that will be ok (especially since time is reported in tenths of an hour). But if anyone else ends up using it, it could be an issue. I'll see if I can find another solution to this. Good call.

**Comment by NotTheEconomist** [comment]
No, ignore this issue. This would be a problem in the naïve case (`time.sleep(1); seconds += 1`) but since the actual time CALCULATION is done precisely (`now – start_time`), the calculation might get done late, but it will be exactly right every time.
